'use strict';

const SyncPlayfabClient = require('./sync_playfab_client');

const sync_server = (title, secret) => {
  const playfab = SyncPlayfabClient(title, secret);

  // This list of commands has been extracted from PlayFabSDK for C#
  const commands = [
    'AddCharacterVirtualCurrency',
    'AddFriend',
    'AddGenericID',
    'AddPlayerTag',
    'AddSharedGroupMembers',
    'AddUserVirtualCurrency',
    'AuthenticateSessionTicket',
    'AwardSteamAchievement',
    'BanUsers',
    'ConsumeItem',
    'CreateSharedGroup',
    'DeleteCharacterFromUser',
    'DeletePlayer',
    'DeletePushNotificationTemplate',
    'DeleteSharedGroup',
    'DeleteUsers',   //This is not in the SDK but it is used in our handler Gameserver/DeletePlayer.js !?
    'DeregisterGame',
    'EvaluateRandomResultTable',
    'ExecuteCloudScript',
    'GetAllSegments',
    'GetAllUsersCharacters',
    'GetCatalogItems',
    'GetCharacterData',
    'GetCharacterInternalData',
    'GetCharacterInventory',
    'GetCharacterLeaderboard',
    'GetCharacterReadOnlyData',
    'GetCharacterStatistics',
    'GetContentDownloadUrl',
    'GetFriendLeaderboard',
    'GetFriendsList',
    'GetLeaderboard',
    'GetLeaderboardAroundCharacter',
    'GetLeaderboardAroundUser',
    'GetLeaderboardForUserCharacters',
    'GetPlayerCombinedInfo',
    'GetPlayerProfile',
    'GetPlayerSegments',
    'GetPlayersInSegment',
    'GetPlayerStatistics',
    'GetPlayerStatisticVersions',
    'GetPlayerTags',
    'GetPlayFabIDsFromFacebookIDs',
    'GetPlayFabIDsFromFacebookInstantGamesIds',
    'GetPlayFabIDsFromGenericIDs',
    'GetPlayFabIDsFromNintendoSwitchDeviceIds',
    'GetPlayFabIDsFromPSNAccountIDs',
    'GetPlayFabIDsFromSteamIDs',
    'GetPlayFabIDsFromXboxLiveIDs',
    'GetPublisherData',
    'GetRandomResultTables',
    'GetServerCustomIDsFromPlayFabIDs',
    'GetSharedGroupData',
    'GetStoreItems',
    'GetTime',
    'GetTitleData',
    'GetTitleInternalData',
    'GetTitleNews',
    'GetUserAccountInfo',
    'GetUserBans',
    'GetUserData',
    'GetUserInternalData',
    'GetUserInventory',
    'GetUserPublisherData',
    'GetUserPublisherInternalData',
    'GetUserPublisherReadOnlyData',
    'GetUserReadOnlyData',
    'GrantCharacterToUser',
    'GrantItemsToCharacter',
    'GrantItemsToUser',
    'GrantItemsToUsers',
    'LinkPSNAccount',
    'LinkServerCustomId',
    'LinkXboxAccount',
    'LoginWithServerCustomId',
    'LoginWithXbox',
    'LoginWithXboxId',
    'ModifyItemUses',
    'MoveItemToCharacterFromCharacter',
    'MoveItemToCharacterFromUser',
    'MoveItemToUserFromCharacter',
    'NotifyMatchmakerPlayerLeft',
    'RedeemCoupon',
    'RedeemMatchmakerTicket',
    'RefreshGameServerInstanceHeartbeat',
    'RegisterGame',
    'RemoveFriend',
    'RemoveGenericID',
    'RemovePlayerTag',
    'RemoveSharedGroupMembers',
    'ReportPlayer',
    'RevokeAllBansForUser',
    'RevokeBans',
    'RevokeInventoryItem',
    'RevokeInventoryItems',
    'SavePushNotificationTemplate',
    'SendCustomAccountRecoveryEmail',
    'SendEmailFromTemplate',
    'SendPushNotification',
    'SendPushNotificationFromTemplate',
    'SetFriendTags',
    'SetGameServerInstanceData',
    'SetGameServerInstanceState',
    'SetGameServerInstanceTags',
    'SetPlayerSecret',
    'SetPublisherData',
    'SetTitleData',
    'SetTitleInternalData',
    'SubtractCharacterVirtualCurrency',
    'SubtractUserVirtualCurrency',
    'UnlinkPSNAccount',
    'UnlinkServerCustomId',
    'UnlinkXboxAccount',
    'UnlockContainerInstance',
    'UnlockContainerItem',
    'UpdateAvatarUrl',
    'UpdateBans',
    'UpdateCharacterData',
    'UpdateCharacterInternalData',
    'UpdateCharacterReadOnlyData',
    'UpdateCharacterStatistics',
    'UpdatePlayerStatistics',
    'UpdateSharedGroupData',
    'UpdateUserData',
    'UpdateUserInternalData',
    'UpdateUserInventoryItemCustomData',
    'UpdateUserPublisherData',
    'UpdateUserPublisherInternalData',
    'UpdateUserPublisherReadOnlyData',
    'UpdateUserReadOnlyData',
    'WriteCharacterEvent',
    'WritePlayerEvent',
    'WriteTitleEvent'
  ];

  const server = {};
  commands.forEach(command => {
    server[command] = playfab(command);
  });

  return server;
};

module.exports = sync_server;
